### ISSUE TITLE
下午马斯克就发了没抛售比特币的推，现在也没通知

### ISSUE THREAD

**Issue by ACTFarsight** [jw-star/elonmusk-twitter-push#2]
好像还是有点问题

**Comment by jw-star** [comment]
> 好像还是有点问题

那是他回复别人的推特，而且没提到狗狗币，代码是没问题的

**Comment by jw-star** [comment]
我加一下关于比特币的相关吧再

**Comment by ACTFarsight** [comment]
那个是他的replies，不是tweets，可能replies没抓取？

**Comment by ACTFarsight** [comment]
打开界面换成https://twitter.com/elonmusk/with_replies可能就行了？

**Comment by jw-star** [comment]
> 打开界面换成[https://twitter.com/elonmusk/with_replies可能就行了？](https://twitter.com/elonmusk/with_replies%E5%8F%AF%E8%83%BD%E5%B0%B1%E8%A1%8C%E4%BA%86%EF%BC%9F)

不行，你可以试下，选择器有问题

**Comment by jw-star** [comment]
> 那个是他的replies，不是tweets，可能replies没抓取？

我试下，就是选择器的问题

**Comment by jw-star** [comment]
测试可以，我再加一下就可以了
